sudo: required
dist: trusty
language: c++

branches:
  only:
   - master
   - devel
   - test

matrix:
  include:
    - os: linux
      compiler: gcc
      env: SIMP_DEBUG=1 SIMP_PROG=mcMd
    - os: linux
      compiler: gcc
      env: SIMP_DEBUG=1 SIMP_PROG=ddMd
    - os: linux
      compiler: gcc
      env: SIMP_DEBUG=1 SIMP_PROG=mcMd_mpi

before_install:
  - sudo apt-get --yes install python
  - sudo apt-get --yes install openmpi-bin
  - sudo apt-get --yes install libopenmpi-dev
  - sudo apt-get --yes install libopenmpi1.6
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/scripts/python
  - export PATH=$PATH:$(pwd)/bin

install:
  - ./setup
  - ./configure -g$SIMP_DEBUG -a1 -d1 -e1
  - if [ "$SIMP_PROG" == "mcMd" ]; then make mcMd; fi
  - if [ "$SIMP_PROG" == "mcMd" ]; then make tools; fi
  - if [ "$SIMP_PROG" == "ddMd" ]; then make ddMd; fi
  - if [ "$SIMP_PROG" == "mcMd_mpi" ]; then make mcMd-mpi; fi

script:
  ./.travis.script
