sudo: required
dist: trusty
language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      env: SMP_G=1
    - os: linux
      compiler: clang
      env: SMP_G=0

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python; fi
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/scripts/python
  - export PATH=$PATH:$(pwd)/bin

install:
  - ./setup
  - ./configure -g$(SMP_G)
  - make mcMd

script:
  - cd $TRAVIS_BLD_DIR/bld/serial/util/tests && make run 
  - cd $TRAVIS_BLD_DIR/bld/serial/simp/tests && make run 
  - cd $TRAVIS_BLD_DIR/bld/serial/mcMd/tests && make run 
